micronaut:
  application:
    name: demo
dataSource:
  url: jdbc:postgresql://db:5432/tt
  driverClassName: org.postgresql.Driver
  username: tt
  password: 'tt'
  pooled: true
  jmxExport: true
hibernate:
  hbm2ddl:
    auto: update
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
